# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *

class Ui_Robot_record(object):
    def setupUi(self, Robot_record):
        Robot_record.setObjectName("Robot_record")
        Robot_record.resize(480, 640)
        self.centralwidget = QtWidgets.QWidget(Robot_record)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 70, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 71, 21))
        self.label_2.setObjectName("label_2")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(40, 520, 89, 25))
        self.save.setObjectName("save")
        self.quitct = QtWidgets.QPushButton(self.centralwidget)
        self.quitct.setGeometry(QtCore.QRect(340, 520, 89, 25))
        self.quitct.setObjectName("quitct")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 220, 111, 21))
        self.label_3.setObjectName("label_3")
        self.showdc1 = QtWidgets.QLineEdit(self.centralwidget)
        self.showdc1.setGeometry(QtCore.QRect(120, 60, 151, 41))
        self.showdc1.setObjectName("showdc1")
        self.showdc2 = QtWidgets.QLineEdit(self.centralwidget)
        self.showdc2.setGeometry(QtCore.QRect(120, 130, 151, 41))
        self.showdc2.setObjectName("showdc2")
        Robot_record.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Robot_record)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 22))
        self.menubar.setObjectName("menubar")
        Robot_record.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Robot_record)
        self.statusbar.setObjectName("statusbar")
        Robot_record.setStatusBar(self.statusbar)

        self.retranslateUi(Robot_record)
        QtCore.QMetaObject.connectSlotsByName(Robot_record)
        self.showdc1.setText
    def retranslateUi(self, Robot_record):
        _translate = QtCore.QCoreApplication.translate
        Robot_record.setWindowTitle(_translate("Robot_record", "MainWindow"))
        self.label.setText(_translate("Robot_record", "Dong co 1:"))
        self.label_2.setText(_translate("Robot_record", "Dong co 2:"))
        self.save.setText(_translate("Robot_record", "Luu vi tri"))
        self.quitct.setText(_translate("Robot_record", "Thoat"))
        self.label_3.setText(_translate("Robot_record", "Duong dan file:"))

    def hienthi(self, Robot_record):


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Robot_record = QtWidgets.QMainWindow()
    ui = Ui_Robot_record()
    ui.setupUi(Robot_record)
    Robot_record.show()
    sys.exit(app.exec_())
